### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by cusiman** [iongpt/LLM-for-Whatsapp#5]
The bot works correctly, now what I want to know is how to make the bot like chatgpt, I mean that you can chat with it and have it respond coherently, or add personality to it. I am using the text generation webui api, I don't know about programming, I just followed the steps to install it.
I appreciate your time and possible response.

**Comment by iongpt** [comment]
You can control the System prompt from LLMSetting.
If you are using text generation webui  make sure that the bot works fine in the UI of Oobabooga. It will work the same via API.
