### ISSUE TITLE
Mac ARM binaries fail to launch

### ISSUE THREAD

**Issue by codel3ss** [iongpt/LLM-for-Whatsapp#6]
The app crashes upon start on MacBook Pro M2 macOS Sonoma 14.2.1

![image](https://github.com/iongpt/LLM-for-Whatsapp/assets/108140987/f3a3325d-764b-410a-b4a1-a09ee64d30f9)

**Comment by iongpt** [comment]
Fixed. New binaries here: https://github.com/iongpt/LLM-for-Whatsapp/releases/download/v1.0.1/WhatsApp-darwin-arm64.zip
